'use strict';
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..'), out = path.join(root, 'release/verification/desktop');
const read = name => JSON.parse(fs.readFileSync(path.join(out, name), 'utf8'));
const verification = read('desktop-verification.json'), integrity = read('package-integrity.json');
assert.equal(verification.result, 'passed'); assert.equal(integrity.result, 'passed');
assert.equal(verification.checks.length, 7); assert.equal(verification.rendererErrors.length, 0);
assert.equal(integrity.runtimeFilesChecked, 68); assert.equal(integrity.images, 33);
const digest = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
assert.equal(digest(fs.readFileSync(integrity.archive)), integrity.archiveSha256, 'Verified ASAR must be unchanged');
const source = path.join(root, 'release/desktop-build/雨停之前_v1.0.0.exe'), target = path.join(root, 'release/雨停之前_v1.0.0.exe');
assert.equal(verification.portable.file, source);
const bytes = fs.readFileSync(source), sha256 = digest(bytes);
assert.equal(bytes.length, verification.portable.bytes);
assert.equal(bytes.subarray(0, 2).toString(), 'MZ');
assert.equal(sha256, digest(fs.readFileSync(path.join(out, '移动后的游戏.exe'))), 'Deliver the actual tested launcher');
fs.copyFileSync(source, target);
assert.equal(digest(fs.readFileSync(target)), sha256);
const report = { product: '雨停之前', version: '1.0.0', platform: 'Windows x64', builtAt: new Date().toISOString(), file: target, bytes: bytes.length, sha256, verification: 'passed', frameless: true, chapters: 23, finalEndings: 13, cards: 74, runtimeFilesChecked: 68, images: 33, checks: verification.checks };
fs.writeFileSync(path.join(out, 'desktop-release.json'), JSON.stringify(report, null, 2));
const record = `# 雨停之前 · 单文件 EXE 验收\n\n验收日期：2026-10-07。\n\n交付文件：${target}\n\n大小：${bytes.length} 字节（${(bytes.length / 1024 / 1024).toFixed(2)} MiB）。SHA-256：\n\n\`${sha256}\`\n\n系统标题栏、菜单栏和原生边框均已移除，窗口边界与内容边界一致。右上角按钮支持最小化、最大化／还原和关闭；F11、Esc 与设置页按钮可切换全屏并恢复原尺寸。\n\n23 个章节模块、13 个最终结局、74 张回忆卡与 33 张图片均保留。实际 ASAR 中的 68 个运行文件逐一校验通过，未包含测试、构建依赖或玩家存档。\n\n实际桌面程序已验收全部 13 个规范结局与收藏列表、全部图片的离线加载、最小窗口布局、真实原生备份下载、文件导入、关闭后重启恢复。另将交付 EXE 复制到不同目录并改名，独立启动便携启动器，检查全屏与退出全屏、同一存档恢复及自定义关闭后的进程退出；交付文件与该实际测试副本的 SHA-256 一致。最终验收无渲染错误，七组检查全部通过。\n\n玩家存档固定保存在 %APPDATA%\\BeforeTheRain。浏览器版存档需在原版设置中导出故事备份，再在桌面版导入。测试使用独立的 test-profile，不读写玩家存档。\n\n记录：desktop-verification.json、package-integrity.json、desktop-release.json。测试过程中发现并修复了去掉原生边框后的全屏状态与窗口尺寸恢复问题；旧失败日志保留用于追踪，最终验收以 desktop-verification.json 为准。\n`;
fs.writeFileSync(path.join(out, 'EXE_验收记录.md'), record);
console.log(JSON.stringify(report, null, 2));
