const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/xing/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {finals,story,engine}=require('./release_fixtures.cjs');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..')),out=path.resolve(__dirname,'../release/verification'),key='before-the-rain-chapter-one-v1:',url='file:///'+path.join(root,'index.html').replace(/\\/g,'/');
let browser;
(async()=>{
 const samples=finals();assert.equal(Object.keys(samples).length,13);for(const s of Object.values(samples))assert.deepEqual(engine.restore(story,s),s);
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[],checks=[],shots=[];page.on('pageerror',e=>errors.push(e.message));
 async function load(s){await page.goto(url);await page.evaluate(({key,s})=>{localStorage.setItem(key+'auto',JSON.stringify({savedAt:new Date().toISOString(),state:s}));localStorage.setItem(key+'settings',JSON.stringify({speed:'instant',music:false,volume:25}));},{key,s});await page.reload();await page.locator('#continue-button').click();}
 async function shot(name){await page.waitForTimeout(2900);await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});shots.push(name+'.png');}
 for(const [id,s]of Object.entries(samples)){await load(s);assert.equal(await page.locator('#ending-title').innerText(),story.endings[id].title);const note=await page.locator('#ending-note').innerText();assert.ok(!note.includes('undefined'));assert.match(note,/秋日尾声已读完/);assert.equal(await page.locator('#next-chapter-button').isVisible(),false);}
 checks.push('all13CanonicalFinalsAndCorrectEndingNotes');await shot('release-final-self');
 await page.locator('[data-panel="gallery"]').click();assert.equal(await page.locator('.gallery-card').count(),74);assert.equal(await page.locator('.gallery-card:not(.locked)').count(),13);await page.locator('#close-panel').click();checks.push('13FinalsCollectedAnd74Cards');
 const saved=await page.evaluate(key=>localStorage.getItem(key+'auto'),key);
 await page.locator('[data-panel="settings"]').click();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export-backup').click()]);const backupFile=path.join(out,'browser-save-backup.json');await download.saveAs(backupFile);const backup=JSON.parse(fs.readFileSync(backupFile,'utf8'));assert.equal(Object.keys(backup.endings).length,13);assert.equal(backup.saves.auto.state.ending,'self_forward');checks.push('backupDownloadContainsProgressAnd13Finals');
 const before=await page.evaluate(key=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith(key)).map(k=>[k,localStorage.getItem(k)])),key);
 const forged=structuredClone(backup);forged.saves.auto.state.flags.s7AutumnKept=false;
 await page.locator('#backup-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(forged))});await page.waitForTimeout(200);const after=await page.evaluate(key=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith(key)).map(k=>[k,localStorage.getItem(k)])),key);assert.deepEqual(after,before);assert.match(await page.locator('#toast').innerText(),/校验/);checks.push('invalidBackupCannotAlterAnyStorage');
 for(const [width,height]of [[1440,900],[390,844],[320,668],[844,390]]){await page.setViewportSize({width,height});await page.waitForTimeout(100);const m=await page.evaluate(()=>({width:document.documentElement.scrollWidth,panelWidth:document.getElementById('panel').getBoundingClientRect().width,contentWidth:document.getElementById('panel-content').scrollWidth,contentClient:document.getElementById('panel-content').clientWidth}));assert.ok(m.width<=width);assert.ok(m.panelWidth<=width);assert.ok(m.contentWidth<=m.contentClient+1);await page.locator('#import-backup').scrollIntoViewIfNeeded();await shot('release-settings-'+width);}
 checks.push('backupSettingsUsableInFourViewports');
 // Import the real downloaded file into an independent storage context, as when moving folders.
 const second=await browser.newContext({viewport:{width:390,height:844}}),other=await second.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto(url);await other.locator('[data-panel="settings"]').click();await other.locator('#backup-file').setInputFiles(backupFile);await other.locator('#confirm-action').click();assert.equal(await other.locator('#title-screen').isVisible(),true);await other.locator('#continue-button').click();assert.equal(await other.locator('#ending-title').innerText(),story.endings.self_forward.title);const imported=await other.evaluate(key=>localStorage.getItem(key+'auto'),key);assert.deepEqual(JSON.parse(imported).state,JSON.parse(saved).state);await other.locator('[data-panel="gallery"]').click();assert.equal(await other.locator('.gallery-card:not(.locked)').count(),13);checks.push('realDownloadedBackupImportedIntoFreshContextAndResumed');
 await page.locator('#close-panel').click();await page.locator('#ending-home-button').click();await page.setViewportSize({width:390,height:844});await shot('release-title-mobile');
 const assets=await page.evaluate(async()=>{const urls=['assets/cover.png',...Object.values(window.RainStory.locations).map(l=>l.image),...window.RainCast.map(p=>'assets/characters/v1/'+p.id+'.png'),'assets/characters/v1/ye_cheng_no_camera.png'];const all=await Promise.all(urls.map(url=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve({url,ok:true});i.onerror=()=>resolve({url,ok:false});i.src=url;})));return {count:all.length,failed:all.filter(x=>!x.ok)};});assert.equal(assets.count,33);assert.equal(assets.failed.length,0);assert.equal(errors.length,0);
 const result={date:new Date().toISOString(),root,checks,assets,errors,screenshots:shots};fs.writeFileSync(path.join(out,root===path.resolve(__dirname,'..')?'release-browser.json':'package-browser.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();});
