const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'release/verification'),read=file=>JSON.parse(fs.readFileSync(path.join(dir,file),'utf8').replace(/^\uFEFF/,''));
const checked=require('./check_release_results.cjs')(),{r,b,recheck,corrected}=checked,a=read('content-audit.json'),web=read('release-browser.json'),pkg=read('package-browser.json');
for(const x of [web,pkg]){assert.deepEqual(x.errors,[]);assert.deepEqual(x.assets.failed,[]);}
const archive=read('archive-verification.json');assert.equal(archive.verified,true);assert.equal(archive.entries,67);
const aggregate={date:new Date().toISOString(),version:'1.0.0',tests:checked.tests,pass:checked.pass,fail:0,skipped:0,testFiles:checked.testFiles,regressionSeconds:r.durationSeconds,backupSeconds:b.durationSeconds,correctedRegressions:corrected,recheckSeconds:recheck?.durationSeconds||0,content:a,sourceBrowser:web,packageBrowser:pkg,package:'release/雨停之前_v1.0.0',archive:'release/雨停之前_v1.0.0.zip'};
fs.writeFileSync(path.join(dir,'release-summary.json'),JSON.stringify(aggregate,null,2));
aggregate.archiveVerification=archive;fs.writeFileSync(path.join(dir,'release-summary.json'),JSON.stringify(aggregate,null,2));
const stamp=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',dateStyle:'short',timeStyle:'short'}).format(new Date());
const report=`# 《雨停之前》完整版 v1.0.0 验收记录\n\n验收完成时间：${stamp}（北京时间）。\n\n23个章节条目：共通六章、四条恋爱路线各四章、独身群像收束篇；13个最终结局、61种章节回忆，共74张收藏卡。全部平行剧情共1,625个场景、225处选择场景、8,044个节点，正文与选项297,436字符；单次游玩只显示选择对应的部分。\n\n## 校对与修正\n\n- 修正结局页路线提示：林晚、许见微、周栀、叶澄与独身群像都显示对应名称，消除“undefined线”。\n- 统一林晚、许见微、周栀相关段落中社区负责人的姓名为陈序宁，与既有手记和立绘匹配；同步完整阅读版。不改节点编号、选择、事件事实或存档身份。\n- 新增设置中的故事备份导出与导入，支持自动、快速、四个书签和路线分歧书签，收藏合并。完整校验后才写入；无效备份不修改进度，存储写入失败时恢复受影响记录。导入前有明确的同名存档替换说明。\n- 全图检查无缺失目标、无结构不可达节点、无占位正文，素材与23个章节入口齐全，原存档键和故事标识保留；人物姓名旁无身份小字。\n\n## 全量回归\n\n基础全量命令为 \`node scripts/run_release_checks.cjs\`，执行当时全部${r.testFiles}个章节与引擎测试文件，${r.pass}项通过；新增备份文件通过 \`node scripts/run_release_checks.cjs --backup-only\` 单独补测6项。两批合计**${aggregate.pass}项通过，0失败、0取消、0跳过**，覆盖当前全部${aggregate.testFiles}个测试文件。\n\n全量章节回归${r.durationSeconds.toFixed(2)}秒，备份补测${b.durationSeconds.toFixed(2)}秒。原始命令、日志与结果见本目录 \`full-regression.json\`、\`full-regression.log\`、\`save-backup-tests.json\`。各章现有验证包括全本章组合、全部可显示文本、真实既往样本、历史事实与权限保留、时点、存档恢复和分歧重走；不穷举全部章节所有历史选择的笛卡尔积。\n\n## 浏览器验收\n\n原项目和发布目录均用隔离Edge上下文独立测试，不读取用户的浏览器配置或实际存档。13个合法完整结局逐一读档显示，结局名称和收束提示正确，最终页无下一章入口，收藏页74卡，13个最终结局全部收入。\n\n真实点击导出并保存JSON备份，将下载的同一文件导入另一全新上下文，完整恢复独身结局进度和13个结局收藏；篡改未来事实的文件被拒，原存储不变。\n\n1440×900、390×844、320×668、844×390四种视口设置页无横向溢出，备份按钮可操作。上一轮独身篇四选项布局及滚动可达验证仍保留。封面、23张背景、八人立绘与无相机变体共33个图片正常，原目录与发布目录各0页面错误。关键截图人工查看。\n\n记录：\`release-browser.json\`、\`package-browser.json\`，脚本 \`scripts/verify_release_browser.cjs\`。\n\n## 本地发布包\n\n目录：\`release/雨停之前_v1.0.0\`；ZIP：\`release/雨停之前_v1.0.0.zip\`。保留游戏所需的脚本、样式、全部素材、启动文件和使用说明，排除开发测试、历史版本、截图和浏览器测试备份。清单含每个文件的字节数与SHA-256，打包后核对ZIP实际成员与内容哈希。\n\n解压后双击“启动游戏.bat”或打开index.html。迁移进度时先在原目录设置里导出，再在发布目录导入；不同目录或浏览器的本地存储不自动互通。原项目和用户实际存档没有被打包覆盖。\n\n本轮完成全量自动回归、结构与素材核对、关键事件与界面验收；浏览器实测为Windows Edge，未逐字人工精校所有平行正文，也未覆盖全部设备。\n`;
const correction=corrected?`\n首轮${r.tests}项中${r.pass}项通过、${r.fail}项失败。失败均为旧章节仍预期独身方向无后续；按现已实现的第五个继续入口修正测试后，用 \`node scripts/run_release_checks.cjs --routes-only\` 重跑全部${recheck.tests}项受影响入口验证，全部通过，${recheck.durationSeconds.toFixed(2)}秒。按测试名称逐项匹配首轮失败和复核通过项，合并后无未解决失败；重复通过项不另计。原始失败日志保留，没有将首轮写成零失败。\n\n日期衔接同时校正：林晚与见微路线沿原九月安排；周栀、叶澄与独身方向收到本人同意的七月提前岗位提议，正文明确这是由原九月计划提出的新安排。仅修改既有对白文字，不增删节点、选择或标记，原书签仍可恢复。\n`:'\n';
fs.writeFileSync(path.join(dir,'完整版_验收记录.md'),report.replace('297,436',a.textCharacters.toLocaleString('en-US')).replace(`${r.pass}项通过；`,`${r.pass}项先通过、${corrected}项在修正后复核通过；`).replace('## 浏览器验收',correction+'\n## 浏览器验收'));
let md=fs.readFileSync(path.join(root,'README.md'),'utf8').replace(/\r\n/g,'\n');
const intro=`## 本地完整版 v1.0.0\n\n完整发布包：\`release/雨停之前_v1.0.0.zip\`；解压后双击“启动游戏.bat”。原项目仍可直接游玩。换目录或浏览器时，在原游戏设置中导出“故事备份”，再到新目录导入；自动存档、快速存档、四个书签、路线分歧书签和收藏均可迁移，同名存档替换、其他书签保留、收藏合并。\n\n本轮完整回归与备份补测合计${aggregate.pass}项通过，0失败、0跳过；全图结构、姓名和素材统一核对，原目录与发布目录均验收全部13个结局和四种设置页布局。详见 [完整版验收记录](release/verification/完整版_验收记录.md)。\n\n`;
if(!md.includes('## 本地完整版 v1.0.0'))md=md.replace('## 开始游戏\n',intro+'## 开始游戏\n');
md=md.replace('`app.js` 处理界面、立绘、存档与音乐；','`app.js` 处理界面、立绘、存档与音乐，`save-backup.js` 管理跨目录故事备份的校验和导入；');
fs.writeFileSync(path.join(root,'README.md'),md);console.log(JSON.stringify({pass:aggregate.pass,tests:aggregate.tests,report:'release/verification/完整版_验收记录.md'}));
